services:
  db:
    image: postgres:13
    container_name: postgres-DB
    environment:
      POSTGRES_DB: TestDB
      POSTGRES_USER: TestUser
      POSTGRES_PASSWORD: TestPassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U TestUser"]
      interval: 10s
      retries: 5

  app:
    image: openjdk:17-jdk-slim
    container_name: image-upload-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=TestUser
      - DB_PASSWORD=TestPassword
    depends_on:
      - db
    networks:
      - mynetwork
volumes:
  db_data:
networks:
  mynetwork: